---

# @todo figure out why this is required
- name: 'PRE Remove ppa:ondrej/php repo (pre main package install) as it breaks other php standard package installs down the road'
  apt_repository:
    repo: 'ppa:ondrej/php'
    state: absent
    update_cache: yes

- name: Install Apache2 and Apache2 modules
  apt: name={{ item }} state=present
  with_items:
   - apache2
   - libapache2-mod-php
  when: webserver_type == "apache"

- name: Install Nginx and Nginx modules
  apt: name={{ item }} state=present
  with_items:
   - nginx
  when: webserver_type == "nginx"  

- name: Install PHP and PHP modules
  apt: name={{ item }} state=present
  with_items:
   - php
   - php-mysql
   - php-fpm
   - php-xml
   - php-mbstring
   - php-dom
   - php-gd
   - php-simplexml 
   - php-xml
   - php-curl
   - software-properties-common  

- name: Resgister the PHP FPM socket path for use in Nginx conf template
  shell: ls /var/run/php/php*.sock
  register: php_fpm_socket_path

- name: Add ppa:ondrej/php repo
  apt_repository:
    repo: 'ppa:ondrej/php'

- name: 'Install php-uploadporogress which is from a seperate repo'    
  apt:
    name: php-uploadprogress
    update_cache: yes
  register: uploadprogress_installed

# @todo figure out why this is required
- name: 'POST Remove ppa:ondrej/php repo (pre main package install) as it breaks other php standard package installs down the road'
  apt_repository:
    repo: 'ppa:ondrej/php'
    state: absent
    update_cache: yes

- name: Install apache2 mod-rewrite 
  apache2_module:
    name: rewrite
    state: present
  when: webserver_type == "apache" 

# - name: Restart Apache2
#   notify:
#    - restart apache2     
#   when: webserver_type == "apache"  
   
# - name: Restart Nginx
#   notify:
#    - restart nginx     
#   when: webserver_type == "nginx" 
