---

- name: Check for D8 Install
  stat: 
    path: "{{ drupal_base_path }}/composer.json"
  register: composer_run    

- name: Make sure drupal_base_path doesn't exist (first run) as Composer needs a blank directory
  when: not composer_run.stat.exists  
  file:
    path: "{{ drupal_base_path }}"
    state: absent

- name: Create D8 base directory before Composer run (using this to allow us to only use one path var)
  file:
    path: "{{ drupal_base_path }}"
    state: directory
    owner: "{{ ansible_user }}"    
    group: "{{ apache_group }}"

- name: Install Drupal 8 with Composer
  become: false
  when: not composer_run.stat.exists
  composer:
    command: create-project
    arguments: drupal/drupal drupal8 --stability stable --no-interaction
    working_dir: "{{ drupal_base_path }}/.."
    prefer_dist: yes

- name: Install Drush with Composer
  become: false    
  composer:
     command: require 
     arguments: drush/drush
     working_dir: "{{ drupal_base_path }}"
